#!/bin/bash
# --with-memory-sanitizer not supported by our compiler.
# configure: error: Valgrind support requested but headers not available
# --with-valgrind 
# configure: error: dtrace command not found on $PATH
# --with-dtrace
./configure --with-trace-refs --with-pydebug --with-assertions --with-address-sanitizer --with-undefined-behavior-sanitizer
